name: Terraform CI

on:
  push:
    branches: [main]

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.5  

    - name: Terraform Format
      run: terraform fmt -check

    - name: Validate Terraform
      run: terraform validate
